package main

/*
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

給定一個字串s，而t為s加上一個隨機生成的小寫字母。求那個被隨機生成的字母

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

func findTheDifference(s string, t string) byte {
	// []rune會回傳 ASCII code
	rs := []rune(s)
	rt := []rune(t)
	// 先將theRune隨機塞入一個數字
	theRune := rt[len(s)]

	// theRune的值為 rt[i] - rs[i]，如此一來最後的差值即為所求值
	for i, _ := range rs {
		theRune -= rs[i]
		theRune += rt[i]
	}

	// 轉型 rune -> byte
	return byte(theRune)
}

func main() {

}

/*
solution:
- https://leetcode.com/problems/find-the-difference/discuss/438736/GoPython-XOR-solution


func findTheDifference(s string, t string) byte {
	var diff byte
	for i := range s {
		diff ^= s[i]
		diff ^= t[i]
	}
	diff ^= t[len(t)-1]
	return diff
}
*/
